### ISSUE TITLE
Funkcje nie działają.

### ISSUE THREAD

**Issue by BD9a** [orzel1244/MultiHack#1]
Po odpaleniu cheata i wybraniu funkcji której chcę używać np. Bhop - enabled, w grze po przytrzymaniu spacji nic się nie dzieje (zwykły skok jak po kliknięciu spacji). Podobnie z innymi funkcjami, glow - enabled, nikogo nie podświetla.

**Comment by orzel1244** [comment]
Powodem jest brak ..... <-- w kropki wstaw coś ;)

Ofc cheat mogę sprzedać wraz z kolejnymi updatami

18.02.2018 10:55 PM "BD9a" <notifications@github.com> napisał(a):

**Comment by orzel1244** [comment]
Drogi panie, jest to błąd z twojej strony, zapewniam że nie jest to bug, lecz ficzer zabezpieczający.
Jeżeli nie chcesz się bawić w obchodzenie moich głupich zabezpieczeń, zapraszam na prv.
